### ISSUE TITLE
ModelNet40 link in dataset is no longer avaliable.

### ISSUE THREAD

**Issue by wonlee2019** [liang3588/MeshMAE#2]
Can you explain some key information about dataset description or how to access the Weblink to get 'ModelNet40' dataset?
As i know, the same name dataset 'ModelNet40' can be accessed from "https://modelnet.cs.princeton.edu/ModelNet40.zip", and i am confused about the difference between the link I post and the link from you post, can you give some advice about that?

**Comment by liang3588** [comment]
We have updated the link and the 'ModelNet40' dataset can be downloaded now. In the dataset downloaded from "https://modelnet.cs.princeton.edu/ModelNet40.zip", many mesh models are non manifold data. Here, we provide the  processed version.

**Comment by wonlee2019** [comment]
> We have updated the link and the 'ModelNet40' dataset can be downloaded now. In the dataset downloaded from "https://modelnet.cs.princeton.edu/ModelNet40.zip", many mesh models are non manifold data. Here, we provide the processed version.

Thanks a lot !
