### ISSUE TITLE
A broken file "ShapeNet-processed/02958343/model_009151-4.obj"

### ISSUE THREAD

**Issue by amiltonwong** [liang3588/MeshMAE#4]
Hi, @liang3588 ,

I downloaded the provided files from ShapeNet-processed. However, after I extract 02958343.zip, the file model_009151-4.obj is corrupted. [Here](https://www.dropbox.com/s/51ss2cftm46wswg/model_009151-4.obj?dl=0) is the corrupted file.

**Comment by liang3588** [comment]
Sorry, I found this problem. I have already refreshed the link, and you can download it. I put the processed ShapeNet dataset on the BaiduYun. If you find any problems with it, I hope you can inform me in time. Thank you!!

**Comment by amiltonwong** [comment]
@liang3588 , thanks a lot! The dataset is OK now.
